openapi: 3.0.3
info:
  title: Cipher-Micro
  description: |-
    This is a simple Cipher Application that will be useful for understanding the basics of AES-GCM encryption.
    
    Some useful links:
    - [The Cipher-Micro repository](https://github.com/fvillegasos/cipher)
  termsOfService: http://swagger.io/terms/
  contact:
    email: francisco.villegasostos@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
tags:
  - name: aes
    description: API for cipher/decipher using the AES-GCM algorithm
    externalDocs:
      description: Find out more
      url: https://iopscience.iop.org/article/10.1088/1742-6596/1019/1/012008/pdf#:~:text=AES%2DGCM%20have%20two%20main,ciphertext%20and%20authentication%20tag%2CT.
paths:
  /aes/generate/key:
    get:
      tags:
        - aes
      summary: Generates a One-time Key for AES encryption/decryption.
      description: This endpoint will generate a random key (One-time Key) that can be used in the encryption/decryption of the text. This key is only for AES algorithm's methods.
      operationId: getAesOtk
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AesOtk'
        '500':
          description: Internal Server Error
  /aes/gcm/cipher:
    post:
      tags:
        - aes
      summary: Cipher a text with AES algorithm
      description: This endpoint will cipher a text using the AES-GCM algorithm
      operationId: getCipheredTextAes
      requestBody:
        description: Text input that will be ciphered and the secret key to do it.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextIn'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextOut'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /aes/gcm/decipher:
    post:
      tags:
        - aes
      summary: Decipher a text with AES algorithm
      description: This endpoint will decipher a text using the AES-GCM algorithm
      operationId: getDecipheredTextAes
      requestBody:
        description: Text input that will be deciphered and the secret key to do it.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextIn'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextOut'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
components:
  schemas:
    AesOtk:
      type: object
      properties:
        otk:
          type: string
          description: One-time Key randonly generated for the cipher/decipher methods of AES algorithm.
          minLength: 32
          maxLength: 32
          example: GV06yH57BDA9kDdBnuJL1Rfjv1cuz+ZJ
      required:
        - otk
    TextIn:
      type: object
      properties:
        otk:
          type: string
          description: One-time Key used for the cipher/decipher the text. This key should have a length of 32 bytes, and should be generated randonly every time.
          minLength: 32
          maxLength: 32
          example: GV06yH57BDA9kDdBnuJL1Rfjv1cuz+ZJ
        text:
          type: string
          description: Text to cipher/decipher
          example: Hello World!/W9Jhfaxz==
      required:
        - otk
        - text
    TextOut:
      type: object
      properties:
        text:
          type: string
          description: Text to cipher/decipher
          example: Hello World!/W9Jhfaxz==
      required:
        - text